fix: NoClassDefFoundError: org/springframework/http/HttpMethod (#552)
* 修复spring HttpMethod类冲突问题

* revert changes: RecordLimiter.java

* remove unused import